coverage:
  paths:
    - coverage.out
  badge:
    path: docs/coverage.svg
  push:
  acceptable: 95%

codeToTestRatio:
  code:
    - "**/*.go"
    - "!**/*_test.go"
  test:
    - "**/*_test.go"

testExecutionTime:
  if: true

comment:
  if: is_pull_request
  hideFooterLink: false

diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}

report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
  hideFooterLink: true
