// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ErrorHandling() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h1>Error Handling</h1><p class=\"lead\">takibi never exposes raw error messages to clients. By default, unhandled errors produce a generic <code>500 Internal Server Error</code> response. Use <code>OnError</code> to customize behavior.</p><h2>Default Behavior</h2><p>Without a custom error handler, any error returned from a handler produces:</p><pre><span class=\"pre-label\">http</span> <code>HTTP/1.1 500 Internal Server Error Content-Type: text/plain Internal Server Error</code></pre><p>Raw error details are never sent to the client &#8212; safe by default.</p><h2>Custom Error Handler</h2><p>Register a global error handler with <code>app.OnError</code>:</p><pre><span class=\"pre-label\">go</span> <code>app.OnError(func(ctx interfaces.IContext[Bindings], err error) error &#123; log.Printf(&#34;handler error: %v&#34;, err) return ctx.Status(http.StatusInternalServerError).Text(&#34;something went wrong&#34;) &#125;)</code></pre><h2>Typed Errors</h2><p>Use standard Go error types to distinguish error categories:</p><pre><span class=\"pre-label\">go</span> <code>app.OnError(func(ctx interfaces.IContext[Bindings], err error) error &#123; var notFound *NotFoundError ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs("if")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `docs/templates/error_handling.templ`, Line: 35, Col: 9}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " errors.As(err, &amp;notFound) &#123; return ctx.Status(404).Text(&#34;not found&#34;) &#125; return ctx.Status(500).Text(&#34;internal error&#34;) &#125;)</code></pre>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
