// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/poteto0/takibi-docs/code"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"hero\"><div class=\"hero-logo\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Logo().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<span class=\"logo-text-hero\">takibi</span></div><p class=\"tagline\">Hono Inspired Type-Safe Context Web Framework for Go</p><h1>Build fast, safe web APIs with type-safe bindings &#8212; deployable on Cloudflare Workers</h1><div class=\"hero-actions\"><a href=\"/getting-started\" class=\"btn btn-primary\">Get Started &#8594;</a> <a href=\"https://github.com/poteto0/takibi\" class=\"btn btn-outline\" target=\"_blank\" rel=\"noopener\">GitHub</a></div><div class=\"hero-code\"><div class=\"dots\"><div class=\"dot dot-red\"></div><div class=\"dot dot-yellow\"></div><div class=\"dot dot-green\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = code.HomeGo().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></section><section class=\"features\"><div class=\"features-inner\"><h2>Why takibi?</h2><p class=\"subtitle\">Inspired by Hono, built for Go</p><div class=\"feature-grid\"><div class=\"feature-card\"><div class=\"feature-icon\">🛡️</div><h3>Type-Safe Context</h3><p>Bindings are fully generic &#8212; no type assertions, no runtime panics. Your IDE knows exactly what your context holds.</p></div><div class=\"feature-card\"><div class=\"feature-icon\">🔥</div><h3>Cloudflare Workers Ready</h3><p>Compile to WASM and deploy with syumai/workers. Zero cold starts, global edge distribution.</p></div><div class=\"feature-card\"><div class=\"feature-icon\">🔒</div><h3>Safe Redirects</h3><p>Built-in protection against open redirects. External hosts require an explicit allowlist.</p></div><div class=\"feature-card\"><div class=\"feature-icon\">⚡</div><h3>Hono-Like API</h3><p>Familiar routing and middleware patterns. If you know Hono, you already know takibi.</p></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
