// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Logo() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<svg viewBox=\"0 0 140 110\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"10\" y=\"62\" width=\"80\" height=\"16\" rx=\"8\" fill=\"#8B4513\" transform=\"rotate(-15 50 70)\"></rect> <rect x=\"10\" y=\"62\" width=\"80\" height=\"16\" rx=\"8\" fill=\"#A0522D\" transform=\"rotate(15 50 70)\"></rect> <path d=\"M 50 18 Q 25 42 28 64 Q 32 78 50 86 Q 68 78 72 64 Q 75 42 50 18 Z\" fill=\"#00ADD8\" opacity=\"0.9\"></path> <path d=\"M 50 30 Q 36 50 38 63 Q 41 75 50 80 Q 59 75 62 63 Q 64 50 50 30 Z\" fill=\"#5DC9E2\" opacity=\"0.9\"></path></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
