// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Routing() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h1>Routing</h1><p class=\"lead\">takibi supports the standard HTTP methods. Routes take a path pattern and a handler function that receives a typed context.</p><h2>HTTP Methods</h2><pre><span class=\"pre-label\">go</span> <code>app.Get(&#34;/users&#34;, listUsers) app.Post(&#34;/users&#34;, createUser) app.Put(&#34;/users/:id&#34;, updateUser) app.Delete(&#34;/users/:id&#34;, deleteUser)</code></pre><h2>Path Parameters</h2><p>Use <code>:name</code> syntax for path parameters, accessed via <code>ctx.Req().PathBy(&#34;name&#34;)</code>:</p><pre><span class=\"pre-label\">go</span> <code>app.Get(&#34;/users/:id&#34;, func(ctx MyContext) error &#123; id := ctx.Req().PathBy(&#34;id&#34;) return ctx.Text(&#34;User: &#34; + id) &#125;)</code></pre><h2>Query Parameters</h2><pre><span class=\"pre-label\">go</span> <code>app.Get(&#34;/search&#34;, func(ctx MyContext) error &#123; q := ctx.Req().QueryBy(&#34;q&#34;) return ctx.Text(&#34;Searching: &#34; + q) &#125;)</code></pre><h2>JSON Response</h2><pre><span class=\"pre-label\">go</span> <code>type User struct &#123; ID   int    `json:&#34;id&#34;` Name string `json:&#34;name&#34;` &#125; app.Get(&#34;/user&#34;, func(ctx MyContext) error &#123; user := User&#123;ID: 1, Name: &#34;takibi&#34;&#125; return ctx.JSON(user) &#125;)</code></pre><h2>Status Codes</h2><pre><span class=\"pre-label\">go</span> <code>app.Post(&#34;/items&#34;, func(ctx MyContext) error &#123; return ctx.Status(201).JSON(newItem) &#125;)</code></pre>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
