// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func GettingStarted() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h1>Getting Started</h1><p class=\"lead\">takibi is a lightweight, type-safe web framework for Go, inspired by Hono. It supports standard HTTP servers and Cloudflare Workers via WASM.</p><h2>Installation</h2><pre><span class=\"pre-label\">shell</span><code>go get github.com/poteto0/takibi</code></pre><h2>Basic Usage</h2><p>Define your bindings struct, create an app, add routes, and fire it up:</p><pre><span class=\"pre-label\">go</span><code>package main import ( &#34;github.com/poteto0/takibi&#34; &#34;github.com/poteto0/takibi/interfaces&#34; ) type Bindings struct &#123; Name string &#125; type MyContext = interfaces.IContext[Bindings] func main() &#123; bindings := &amp;Bindings&#123;Name: &#34;World&#34;&#125; app := takibi.New(bindings) app.Get(&#34;/hello&#34;, func(ctx MyContext) error &#123; return ctx.Text(&#34;Hello, &#34; + ctx.Env().Name) &#125;) ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs("if")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `public/templates/getting_started.templ`, Line: 32, Col: 10}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " err := app.Fire(&#34;:8000&#34;); err != nil &#123; panic(err) &#125; &#125;</code></pre><h2>Run It</h2><pre><span class=\"pre-label\">shell</span><code>go run main.go curl http://localhost:8000/hello # Hello, World</code></pre><h2>Next Steps</h2><p>Explore the core concepts and features:</p><ul style=\"list-style:none;display:flex;flex-direction:column;gap:8px;margin-top:8px;\"><li><a href=\"/docs/type-safe-context\" style=\"color:var(--primary);text-decoration:none;font-size:15px;\">&#8594; Type-Safe Context</a></li><li><a href=\"/docs/routing\" style=\"color:var(--primary);text-decoration:none;font-size:15px;\">&#8594; Routing</a></li><li><a href=\"/docs/redirect\" style=\"color:var(--primary);text-decoration:none;font-size:15px;\">&#8594; Redirect</a></li><li><a href=\"/docs/error-handling\" style=\"color:var(--primary);text-decoration:none;font-size:15px;\">&#8594; Error Handling</a></li><li><a href=\"/docs/request-body\" style=\"color:var(--primary);text-decoration:none;font-size:15px;\">&#8594; Request Body Size Limit</a></li></ul>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
