// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Redirect() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h1>Redirect</h1><p class=\"lead\">takibi provides two redirect methods with distinct security semantics &#8212; safe-by-default internal redirects, and explicit external redirects with an allowlist.</p><h2>Internal Redirect</h2><p><code>ctx.Redirect(path)</code> only accepts relative paths. Passing an absolute URL or external host returns an error, preventing open redirect vulnerabilities:</p><pre><span class=\"pre-label\">go</span><code>app.Get(&#34;/dashboard&#34;, func(ctx MyContext) error &#123; return ctx.Redirect(&#34;/home&#34;)  // safe: relative path &#125;) ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs("//")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `public/templates/redirect.templ`, Line: 12, Col: 6}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " This will return an error &#8212; absolute URLs are rejected ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs("//")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `public/templates/redirect.templ`, Line: 13, Col: 6}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " ctx.Redirect(&#34;https://evil.com&#34;)</code></pre><div class=\"callout\"><code>Redirect</code> enforces relative paths at the framework level. You cannot accidentally redirect to an external host.</div><h2>External Redirect</h2><p>For legitimate external redirects (OAuth callbacks, cross-domain flows), use <code>ctx.RedirectExternal(url, allowlist)</code>. The target host must appear in the allowlist:</p><pre><span class=\"pre-label\">go</span><code>type Bindings struct &#123; AllowedRedirectHosts []string &#125; func main() &#123; bindings := &amp;Bindings&#123; AllowedRedirectHosts: []string&#123;&#34;auth.example.com&#34;&#125;, &#125; app := takibi.New(bindings) app.Get(&#34;/oauth/callback&#34;, func(ctx MyContext) error &#123; next := ctx.Req().QueryBy(&#34;next&#34;) return ctx.RedirectExternal(next, ctx.Env().AllowedRedirectHosts) &#125;) &#125;</code></pre><div class=\"callout warning\">If the target host is not in the allowlist, <code>RedirectExternal</code> returns an error. Always restrict your allowlist to known, trusted domains.</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
