// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func RequestBody() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h1>Request Body</h1><p class=\"lead\">takibi enforces a configurable request body size limit to protect against DoS attacks via large payloads. The default limit is <strong>10 MiB</strong>.</p><h2>Default Limit</h2><p><code>ctx.Req().Unmarshall()</code> automatically limits body reads to <code>constants.DefaultMaxBodyBytes</code> (10 MiB). No configuration required:</p><pre><span class=\"pre-label\">go</span><code>app.Post(&#34;/data&#34;, func(ctx MyContext) error &#123; var payload MyPayload ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs("if")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `public/templates/request_body.templ`, Line: 10, Col: 10}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " err := ctx.Req().Unmarshall(&amp;payload); err != nil &#123; return err // bodies over 10 MiB are rejected automatically &#125; return ctx.JSON(payload) &#125;)</code></pre><h2>Custom Limit</h2><p>Use <code>takibi.NewWithOption</code> to configure the limit for your use case:</p><pre><span class=\"pre-label\">go</span><code>app := takibi.NewWithOption(bindings, takibi.TakibiOption&#123; MaxBodyBytes: 4 &lt;&lt; 20, // 4 MiB &#125;)</code></pre><h2>Handling Oversized Requests</h2><p>When the limit is exceeded, <code>Unmarshall</code> returns an <code>*http.MaxBytesError</code>:</p><pre><span class=\"pre-label\">go</span><code>app.Post(&#34;/upload&#34;, func(ctx MyContext) error &#123; var payload MyPayload ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs("if")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `public/templates/request_body.templ`, Line: 24, Col: 10}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " err := ctx.Req().Unmarshall(&amp;payload); err != nil &#123; var maxErr *http.MaxBytesError ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs("if")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `public/templates/request_body.templ`, Line: 26, Col: 14}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " errors.As(err, &amp;maxErr) &#123; return ctx.Status(http.StatusRequestEntityTooLarge). Text(&#34;request body too large&#34;) &#125; return err &#125; return ctx.Text(&#34;ok&#34;) &#125;)</code></pre><div class=\"callout\"><code>takibi.New</code> uses the 10 MiB default. Only use <code>NewWithOption</code> when you need a different limit.</div><h2>Limit Reference</h2><table><thead><tr><th>Constructor</th><th>Body Limit</th></tr></thead> <tbody><tr><td><code>takibi.New(bindings)</code></td><td>10 MiB (default)</td></tr><tr><td><code>takibi.NewWithOption(b, opt)</code></td><td>Configurable via <code>opt.MaxBodyBytes</code></td></tr></tbody></table>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
