// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func TypeSafeContext() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h1>Type-Safe Context</h1><p class=\"lead\">takibi&#39;s defining feature. Your application bindings &#8212; environment variables, database clients, configuration &#8212; are typed at compile time and accessible through the context.</p><h2>The Problem</h2><p>In typical Go web frameworks, shared state lives in a generic map or requires unsafe type assertions:</p><pre><span class=\"pre-label\">go</span><code>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs("//")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `public/templates/type_safe_context.templ`, Line: 8, Col: 51}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " typical framework &#8212; no type safety ctx.Set(&#34;db&#34;, db) db := ctx.Get(&#34;db&#34;).(*sql.DB) // panic risk at runtime</code></pre><h2>The takibi Way</h2><p>Define a <code>Bindings</code> struct and pass it to <code>takibi.New</code>. Every handler receives a fully typed context:</p><pre><span class=\"pre-label\">go</span><code>type Bindings struct &#123; DB     *sql.DB Config AppConfig Greet  func(name string) string &#125; type MyContext = interfaces.IContext[Bindings] func main() &#123; bindings := &amp;Bindings&#123; DB:     openDB(), Config: loadConfig(), Greet:  func(name string) string &#123; return &#34;Hello, &#34; + name &#125;, &#125; app := takibi.New(bindings) app.Get(&#34;/greet&#34;, func(ctx MyContext) error &#123; ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs("//")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `public/templates/type_safe_context.templ`, Line: 31, Col: 14}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " 100% compile-time safe &#8212; no type assertions msg := ctx.Env().Greet(&#34;takibi&#34;) return ctx.Text(msg) &#125;) &#125;</code></pre><div class=\"callout\">The <code>Env()</code> method returns your <code>Bindings</code> value directly. No casts, no panics.</div><h2>Cloudflare Workers Bindings</h2><p>When deploying to Cloudflare Workers, bindings map directly to Workers environment variables and KV namespaces:</p><pre><span class=\"pre-label\">go</span><code>type Bindings struct &#123; MyKV   workers.KVNamespace Secret string &#125; ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs("//")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `public/templates/type_safe_context.templ`, Line: 46, Col: 6}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " ctx.Env().MyKV is the Workers KV binding &#8212; typed, always.</code></pre>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
